factor     ::= number | ident
operand    ::= "+" | "-" | "*"
term       ::= factor { "*" factor }
expr       ::= term { ("+" | "-") term }
decl       ::= "i32" [ "mut" ] ident "{" expr "}"
assign     ::= ident ":=" expr
statement  ::= decl | assign | "\n"
exitStmt   ::= "exit" factor
program    ::= { statement } exitStmt