value      ::= number | ident
operand    ::= "+" | "-" | "*"
expr       ::= value [ operand value ]
decl       ::= "i32" [ "mut" ] ident "{" expr "}"
assign     ::= ident ":=" expr
statement  ::= decl | assign | "\n"
exitStmt   ::= "exit" value
program    ::= { statement } exitStmt